version: 0.0
os: linux	
files:	
  - source: /index.php	  
    destination: /var/www/html/	    
hooks:	
  BeforeInstall:	 
    - location: /scripts/install_dependencies	   
      timeout: 300	     
      runas: root	     
    - location: /install_composer_dependencies	   
      timeout: 300	     
      runas: root	     
    - location: /scripts/start_server	    
      timeout: 300	     
      runas: root	      
