version: 0.2
phases:
 install:
   commands:
     - yum update 
     - yum install php7.4 -y 
 build:
   commands:
     - echo Build started on `date`
     - zip index.zip ./index.php
artifacts:
  type: 
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - aws.gif
    - back.jpg
