version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.php
artifacts:
  type: null
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - 1.png
    - aws.gif
    - back.jpg
