version: 0.2
phases:
 install:
   commands:
     - yum update 
     - yum install -y amazon-linux-extras
     - yum install php7.4 -y 
     - yum clean metadata
     - yum install php php-{pear,cgi,common,curl,mbstring,gd,mysqlnd,gettext,bcmath,json,xml,fpm,intl,zip,imap}
 build:
   commands:
     - echo Build started on `date`
     - zip index.zip ./index.php
artifacts:
  type: 
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - aws.gif
    - back.jpg
